In [142]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [143]:
df = pd.read_csv('train.csv')

In [144]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [145]:
df = pd.read_csv('train.csv')[['Age','Fare','Pclass','Survived']]

In [146]:
df.head(4)

    Age     Fare  Pclass  Survived
0  22.0   7.2500       3         0
1  38.0  71.2833       1         1
2  26.0   7.9250       3         1
3  35.0  53.1000       1         1

In [147]:
set = df.sample(50)

In [148]:
set.head()

      Age     Fare  Pclass  Survived
123  32.5  13.0000       2         1
840  20.0   7.9250       3         0
228  18.0  13.0000       2         0
420   NaN   7.8958       3         0
158   NaN   8.6625       3         0

In [152]:
set.isnull().sum()

Age         13
Fare         0
Pclass       0
Survived     0
dtype: int64

In [153]:
new_set = set

In [158]:
new_set = new_set.fillna(new_set.mean())

In [159]:
new_set.head()

           Age     Fare  Pclass  Survived
123  32.500000  13.0000       2         1
840  20.000000   7.9250       3         0
228  18.000000  13.0000       2         0
420  30.671081   7.8958       3         0
158  30.671081   8.6625       3         0

In [160]:
new_set.isnull().sum()

Age         0
Fare        0
Pclass      0
Survived    0
dtype: int64

In [161]:
lr = LinearRegression()
lr

LinearRegression()

In [162]:
from sklearn.model_selection import train_test_split

In [163]:
set.isnull().sum()

Age         13
Fare         0
Pclass       0
Survived     0
dtype: int64

In [168]:
missing_mask = set['Age'].isna()

In [171]:
features = ['Fare', 'Pclass', 'Survived']

x_train = set.loc[~missing_mask, features]

In [172]:
x_train.head()

       Fare  Pclass  Survived
123  13.000       2         1
840   7.925       3         0
228  13.000       2         0
200   9.500       3         0
494   8.050       3         0

In [173]:
y_train = set.loc[~missing_mask, ['Age']]

In [174]:
y_train.head(3)

      Age
123  32.5
840  20.0
228  18.0

In [175]:
lr

LinearRegression()

In [176]:
lr.fit(x_train,y_train)

LinearRegression()

In [177]:
X_pred = new_set.loc[missing_mask, features]

In [189]:
y_pred = lr.predict(X_pred)

In [181]:
y_pred = pd.DataFrame(y_pred)

In [191]:
y_pred

array([[21.60431614],
       [21.63466525],
       [21.59854478],
       [44.19876557],
       [44.85190294],
       [22.53638818],
       [21.89525915],
       [21.60431614],
       [22.55700357],
       [43.89344415],
       [21.59854478],
       [43.84448803],
       [43.22051474]])

In [183]:
from sklearn.metrics import accuracy_score

In [192]:
new_set.head()

           Age     Fare  Pclass  Survived
123  32.500000  13.0000       2         1
840  20.000000   7.9250       3         0
228  18.000000  13.0000       2         0
420  30.671081   7.8958       3         0
158  30.671081   8.6625       3         0

In [185]:
set.head()

       Age     Fare  Pclass  Survived
123  32.50  13.0000       2         1
840  20.00   7.9250       3         0
228  18.00  13.0000       2         0
420    NaN   7.8958       3         0
158    NaN   8.6625       3         0
593    NaN   7.7500       3         0
200  28.00   9.5000       3         0
494  21.00   8.0500       3         0
244  30.00   7.2250       3         0
204  18.00   8.0500       3         1
55     NaN  35.5000       1         1
136  19.00  26.2833       1         1
417  18.00  13.0000       2         1
292  36.00  12.8750       2         0
182   9.00  31.3875       3         0
669    NaN  52.0000       1         1
473  23.00  13.7917       2         1
769  32.00   8.3625       3         0
637  31.00  26.2500       2         0
36     NaN   7.2292       3         1
140    NaN  15.2458       3         0
197  42.00   8.4042       3         0
796  49.00  25.9292       1         1
349  42.00   8.6625       3         0
339  45.00  35.5000       1         0
622  20.00  15.7417       3         1
525  40.50   7.7500       3         0
223    NaN   7.8958       3         0
462  47.00  38.5000       1         0
458  50.00  10.5000       2         1
658  23.00  13.0000       2         0
642   2.00  27.9000       3         0
138  16.00   9.2167       3         0
300    NaN   7.7500       3         1
475    NaN  52.0000       1         0
78    0.83  29.0000       2         1
191  19.00  13.0000       2         0
754  48.00  65.0000       2         1
459    NaN   7.7500       3         0
259  50.00  26.0000       2         1
645  48.00  76.7292       1         1
141  22.00   7.7500       3         1
30   40.00  27.7208       1         0
507    NaN  26.5500       1         1
66   29.00  10.5000       2         1
351    NaN  35.0000       1         0
599  49.00  56.9292       1         1
630  80.00  30.0000       1         1
509  26.00  56.4958       3         1
542  11.00  31.2750       3         0

In [188]:
y_pred

            0
0   21.604316
1   21.634665
2   21.598545
3   44.198766
4   44.851903
5   22.536388
6   21.895259
7   21.604316
8   22.557004
9   43.893444
10  21.598545
11  43.844488
12  43.220515

In [193]:
set.loc[missing_mask,'Age'] = y_pred

In [194]:
set.head()

           Age     Fare  Pclass  Survived
123  32.500000  13.0000       2         1
840  20.000000   7.9250       3         0
228  18.000000  13.0000       2         0
420  21.604316   7.8958       3         0
158  21.634665   8.6625       3         0